### ISSUE TITLE
Memory error when executing Stage 3.

### ISSUE THREAD

**Issue by ktjaco** [goatsweater/nrn-rrn#29]
When executing Stage 3 (`src/stage_3.py`) on the Saskatchewan dataset, I receive a Memory Error related to the Pandas `.merge` method. I have tested this on the New Brunswick dataset and I did not receive this error.

I have tried this on both Linux and Windows OS.

```
2020-05-13 14:07:12 - INFO: Finished. Time elapsed: 0:02:00.159149.
Traceback (most recent call last):
  File "stage_3.py", line 559, in <module>
    main()
  File "/home/kent/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kent/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kent/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kent/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "stage_3.py", line 552, in main
    stage.execute()
  File "stage_3.py", line 533, in execute
    self.roadseg_gen_full()
  File "stage_3.py", line 264, in roadseg_gen_full
    addrange, how="left", left_on="adrangenid", right_on="nid", suffixes=("", "_addrange")).merge(
  File "/home/kent/.local/lib/python3.6/site-packages/geopandas/geodataframe.py", line 616, in merge
    result = DataFrame.merge(self, *args, **kwargs)
  File "/home/kent/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 7323, in merge
    validate=validate,
  File "/home/kent/.local/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 84, in merge
    return op.get_result()
  File "/home/kent/.local/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 643, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/home/kent/.local/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 860, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()
  File "/home/kent/.local/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 839, in _get_join_indexers
    self.left_join_keys, self.right_join_keys, sort=self.sort, how=self.how
  File "/home/kent/.local/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 1321, in _get_join_indexers
    return join_func(lkey, rkey, count, **kwargs)
  File "pandas/_libs/join.pyx", line 96, in pandas._libs.join.left_outer_join
MemoryError
```

![memerror](https://user-images.githubusercontent.com/14288239/81854325-cafe0980-952b-11ea-8c15-25b0689d43bd.png)

**Comment by jessestewart1** [comment]
This is due to having excessive records with missing / default values for the nid grouping fields (namebody, dirprefix, dirsuffix, strtypre, strtysuf, starticle). For instance, SK has about 72% of records with all Unknowns for these fields.

Currently implementing logic to handle this.

**Comment by jessestewart1** [comment]
The fix involves splitting any group (grouped by match fields) above 10,000 into smaller groups of 1,000. It's technically incorrect to split these records like this because we don't know if they're connected, but the problem is that correctly applying the nid logic with such a large group causes the memory error. In reality, this isn't an issue though, because only a dataset with an absurd amount of Unknown street names will have this scenario.
